### ISSUE TITLE
Getting java.lang.ExceptionInInitializerError and   java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by soumyarout** [BarcodeEye/BarcodeEye#4]
Hi Guys,
I have tried this in Glass but it is not working. Giving following mentioned exception. Please let me know am I missing something ?

01-31 12:30:30.506: E/AndroidRuntime(14798): FATAL EXCEPTION: main
01-31 12:30:30.506: E/AndroidRuntime(14798): java.lang.ExceptionInInitializerError
01-31 12:30:30.506: E/AndroidRuntime(14798):    at com.github.barcodeeye.LaunchActivity.processVoiceAction(LaunchActivity.java:42)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at com.github.barcodeeye.LaunchActivity.access$0(LaunchActivity.java:37)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at com.github.barcodeeye.LaunchActivity$1.run(LaunchActivity.java:30)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at android.os.Handler.handleCallback(Handler.java:624)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at android.os.Handler.dispatchMessage(Handler.java:92)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at android.os.Looper.loop(Looper.java:137)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at android.app.ActivityThread.main(ActivityThread.java:4424)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at java.lang.reflect.Method.invokeNative(Native Method)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at java.lang.reflect.Method.invoke(Method.java:511)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
01-31 12:30:30.506: E/AndroidRuntime(14798):    at dalvik.system.NativeStart.main(Native Method)
01-31 12:30:30.506: E/AndroidRuntime(14798): Caused by: java.lang.NoClassDefFoundError: com.google.zxing.ResultMetadataType
01-31 12:30:30.506: E/AndroidRuntime(14798):    at com.github.barcodeeye.scan.CaptureActivity.<clinit>(CaptureActivity.java:71)
01-31 12:30:30.506: E/AndroidRuntime(14798):    ... 12 more

**Comment by jromero** [comment]
Are you compiling from source? If so it's most likely that the zxing library is not being exported. Can you check your classpath? Also, you can reference and get the latest apk from https://drone.io/github.com/BarcodeEye/BarcodeEye/files

**Comment by soumyarout** [comment]
Yes i made a clone of this project and imported to Eclipse. I have checked the build-path zxing-core-2.3.jar is added to class path. As you suggested I have tried the https://drone.io/github.com/BarcodeEye/BarcodeEye/files/bin/BarcodeEye-debug.apk as well. It is crashing too.

**Comment by soumyarout** [comment]
Finally I have managed to run this. Actually the issue with the Zxing core jar. Imported the core sources and added to build path. 

Thanks for this library it is working fine.
