### ISSUE TITLE
Latest version crashes when used

### ISSUE THREAD

**Issue by framerate** [BarcodeEye/BarcodeEye#5]
Is this a known issue? 

"Ok Glass -> Scan a Barcode -> Barcodeeye has stopped, tap to continue"

**Comment by guilzriel** [comment]
You need to include your .java file in your manifest.xml (at least that was my issue when i saw it)

**Comment by framerate** [comment]
Oh, the README makes it sound like a self contained application. I wasn't looking for a lib, just a barcode scanner :/
